name: Auto Release
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Cache go module
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies, run test
      run: |
        go test ./...

    - name: Build
      env:
        NAME: robot
        BINDIR: bin
        CGO_ENABLED: 0
      run: go build -o robot main.go

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: robot
        draft: true
